name: My Action
description: Runs a command of your choice
author: frigus02
inputs: 
  command:
    description: Command to run
    required: true
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.command }}
